#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          sickrage
# Required-Start:    $local_fs $remote_fs $syslog sabnzbd
# Required-Stop:     $local_fs $remote_fs $syslog sabnzbd
# Should-Start:      kodi
# Should-Stop:       kodi
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of SickRage
# Description:       starts instance of SickRage
### END INIT INFO

# Modified by: Orkun Sensebat <ihate88@gmail.com>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.


NAME=sickrage
DAEMON=/opt/sickrage/SickBeard.py
DESC="SickRage"

PID_FILE=/var/run/$NAME.pid

test -x $DAEMON || exit 0

if test -f /etc/default/$NAME; then
    . /etc/default/$NAME
fi

DAEMON_OPTS=" --daemon --datadir=$DATA_PATH"

. /lib/lsb/init-functions

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" || true
        if start-stop-daemon -d /opt/sickrage --start -c $USER --group=$GROUP --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS; then
		log_end_msg 0 || true
	else
		log_end_msg 1 || true
	fi
        ;;
  stop)
	log_daemon_msg "Stopping $DESC" || true
        if start-stop-daemon --stop --pidfile $PID_FILE; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
  restart|force-reload)
	log_daemon_msg "Restarting $DESC" || true
        start-stop-daemon --stop --pidfile $PID_FILE
        sleep 5
        if start-stop-daemon -d /opt/sickrage --start -c $USER --group=$GROUP --background --pidfile $PID_FILE  --make-pidfile --exec $DAEMON -- $DAEMON_OPTS; then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
  *)
        N=/etc/init.d/$NAME
        log_action_msg "Usage: $N {start|stop|restart|force-reload}" || true
        exit 1
        ;;
esac

exit 0
