#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          xbmc_hama_mce
# Required-Start:    $local_fs $remote_fs $syslog
# Required-Stop:     $local_fs $remote_fs $syslog
# Should-Start:      udev
# Should-Stop:       udev
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hama MCE event client
# Description:       Hama MCE event client for Kodi Home Theatre
### END INIT INFO

# Modified by:       Orkun Sensebat <ihate88@gmail.com>
#
# Please remove the "Author" lines above and replace them
# with your own name if you copy and modify this script.

NAME=xbmc_hama_mce
DAEMON=/usr/bin/xbmc_hama_mce
DESC="XBMC HAMA MCE event client"

PID_FILE=/var/run/$NAME.pid

DEAMON_OPTS="-d"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
        log_daemon_msg "Starting $DESC"
        start-stop-daemon --start --quiet --background --pidfile $PID_FILE --make-pidfile --exec $DAEMON -- $DEAMON_OPTS 
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping $DESC"
        start-stop-daemon --stop --exec $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
        $0 stop
        $0 start
    ;;
  reload)
        killall -HUP $DAEMON
    ;;
  *)  
    echo "Usage: $0 {start|stop|restart|force-reload|reload}"
    exit 1
    ;;
esac

exit 0
    
